USE GENERACION33

IF NOT EXISTS (SELECT name FROM sys.indexes WHERE name = 'IX_Users_Email')
BEGIN
	CREATE UNIQUE NONCLUSTERED INDEX
	IX_Users_Email
	ON Usuario(Email);
END

CREATE TABLE Roles (
	Id INT PRIMARY KEY IDENTITY,
	Nombre NVARCHAR(50) NOT NULL,
	Descripcion NVARCHAR(50)
	)
	
INSERT INTO Roles Values
('Admin','Administradores'),
('User','Usuario')

ALTER TABLE Usuario
ADD IdRol INT NOT NULL DEFAULT 2;

ALTER TABLE Usuario 
ADD CONSTRAINT Fk_Usuario_Roles
FOREIGN KEY (IdRol) REFERENCES Roles(Id)

ALTER TABLE Usuario
ALTER COLUMN Email VARCHAR(50) NOT NULL;

SELECT*FROM Usuario U
INNER JOIN Roles R ON U.IdRol = R.Id

--UPDATE Usuario SET IDROL = 1 WHERE IdUsuario = 1